training:
  seed: 42
  output_dir: ../models/qlora
  plm_name: facebook/mbart-large-50
  src_lang: en_XX
  tgt_lang: ko_KR
  use_fsdp: False
  max_length: 384
  dataloader_num_workers: 4
  per_device_batch_size: 4
  save_total_limit: 2
  num_epochs: 2
  learning_rate: 2e-5
  lr_scheduler_type: linear
  optim: paged_adamw_32bit
  gradient_accumulation_steps: 4
  gradient_checkpointing: False
  max_grad_norm: 0.3
  warmup_ratio: 0.1
  weight_decay: 0.01
  fp16: False # at least one of fp16 / bf16 should be False
  bf16: True # at least one of fp16 / bf16 should be False
  logging_dir: ./logs
  logging_strategy: steps
  evaluation_strategy: steps
  save_strategy: steps
  logging_steps: 25
  eval_steps: 1000 # warmup_steps(total_steps의 10%)로 대체
  save_steps: 1000 # warmup_steps(total_steps의 10%)로 대체
  report_to: wandb
  load_best_model_at_end: True
  metric_for_best_model: SacreBLEU
  just_test: False

data:
  dataset_name: traintogpb/aihub-koen-translation-integrated-tiny-100k

qlora:
  use_4bit: True
  use_8bit: False
  bnb_4bit_quant_type: nf4
  bnb_4bit_compute_dtype: bfloat16
  use_double_quant: True
  lora_alpha: 16
  lora_dropout: 0.1
  lora_r: 64
  lora_target_modules:
    - q_proj
    - k_proj
    - v_proj
    - out_proj
    - base_layer
    - fc2
    - fc1

general:
  project_name: ojt_translation
  run_name: mbart-qlora
  